### ISSUE TITLE
Minimum Viable Product - Building the Website

### ISSUE THREAD

**Issue by IrisFleischer** [orchid-initiative/orchid-website#27]
## User Stories
As an employee of Orchid, I want a website for our organization published so I can use my experience here on my resume. 

As someone curious about Orchid, I would like a website so I can know how to get involved with the initiative and make a difference.

## Acceptance Criteria
In descending order of priority: 

- [x] The website no longer has any images from the template
- [x] The main pages outlined in the [Website Breakdown](https://docs.google.com/document/d/1rlOseqHcGHrkkIN5ICiYyfMvjyoxoUHaKQd5cfejnIw/edit#heading=h.g5i8tchy5xc) file have been created
   - [x] Fill out the Volunteer page sections with the website breakdown outline
   - [x] Review Internship page, referencing website breakdown outline
- [x] There are functional buttons and links where necessary
   > NOTE: Links/buttons to resources we do not yet have such as company email addresses do not have to be functional
- [x] There is sample text as the content in each page
   > Functional description of each section - it doesn't need to sound good, just get the point across, the purpose of each section.
   - [x] Functional description of the volunteer section
   - [x] Functional description of the goal of the projects in "Our Work" 
   - [x] Functional description of "Active Projects" and "Past Projects" 
   - [x] Project description template: 
      > Project Title
      > Brief description on the goal of the project
   - [x] Functional description of the internships

**Comment by rileeki** [comment]
Some progress, but need to finish removing template text.  I need to remember not to go down rabbit holes - just get some basic sentences up!  Goal to work on the remaining bits this afternoon and Sunday.  Tuesday is our next scrum meeting, and hopefully I'll be ready for the next priority then.
