### ISSUE TITLE
Text document

### ISSUE THREAD

**Issue by IrisFleischer** [orchid-initiative/orchid-website#35]
## Request
"Are any of texts written somewhere in a document? I can work on making them concise! If not, I can find another way. I just don’t want to go to the page and start changing things."
\- Kai
## Acceptance Criteria
- [x] There is a google doc located in the website project folder containing all the body text in the website
   > This may include labels, but does not have to.
- [x] The text is sorted by page and category
   > Similar to the [Website Breakdown](https://docs.google.com/document/d/1rlOseqHcGHrkkIN5ICiYyfMvjyoxoUHaKQd5cfejnIw/edit?usp=drive_link) document

**Comment by rileeki** [comment]
Orchid Initiative/Projects - Active/Orchid Website Project/[Website Text](https://docs.google.com/document/d/1azh5K0bvbI_mjdfWUvD3_TEAfSF9dXrULiVcQyosdRg/edit?usp=sharing)
